spring:
  jpa:
    database-platform: ex.rr.tasklist.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:sqlite:tasklist.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
