spring:
  jpa:
    database-platform: ex.rr.tasklist.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 64KB
      max-request-size: 64KB

  datasource:
    url: jdbc:sqlite:tasklist.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:tasklist.p12
    key-store-password: password
    keyStoreType: PKCS12